services:
  plataforma-chopp:
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: build
    restart: always
    ports:
      - "8004:8004"
    # env_file:
    #   - stack.env
    networks:
      - pi_default
    volumes:
      - plataforma_chopp_data:/var/lib/postgresql/data
      - plataforma_chopp_app:/app/media
volumes:
  plataforma_chopp_data:
  plataforma_chopp_app:
networks:
  pi_default:
    external: true