# Generated by Django 5.1.7 on 2025-03-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventoRealizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(blank=True, default='esse texto aparecerá abaixo da imagem', max_length=30)),
                ('imagem', models.ImageField(upload_to='eventos/')),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ImagemSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='slides/')),
                ('tipo', models.CharField(default='Evento', max_length=50)),
            ],
        ),
    ]
