# Generated by Django 5.1.6 on 2025-03-08 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemslide',
            name='tipo',
            field=models.CharField(default='Evento', max_length=50),
        ),
    ]
