# Generated by Django 5.1.7 on 2025-03-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_imagemslide_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemslide',
            name='imagem',
            field=models.ImageField(upload_to='slides/'),
        ),
    ]
