# Generated by Django 5.1.7 on 2025-03-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('taxa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frete', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(default='descreva o produto/serviço', max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('litros', models.PositiveIntegerField(blank=True, null=True)),
                ('imagem', models.ImageField(blank=True, default=None, null=True, upload_to='media/')),
                ('servico', models.BooleanField(default=False)),
                ('disponivel', models.BooleanField(default=True)),
                ('destaque', models.BooleanField(default=False)),
                ('promo', models.BooleanField(default=False)),
                ('premium', models.BooleanField(default=False)),
                ('mais_vendido', models.BooleanField(default=False)),
            ],
        ),
    ]
