# Generated by Django 5.1.1 on 2025-02-08 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(default='descreva a peça', max_length=255)),
                ('disponivel', models.BooleanField(default=True)),
                ('destaque', models.BooleanField(default=False)),
                ('promo', models.BooleanField(default=False)),
                ('premium', models.BooleanField(default=False)),
                ('mais_vendido', models.BooleanField(default=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('imagem', models.ImageField(upload_to='produtos')),
                ('tamanho', models.CharField(max_length=3)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.categoria')),
            ],
        ),
    ]
