# Generated by Django 5.1.1 on 2024-10-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='tamanho',
            field=models.CharField(default='M', max_length=3),
        ),
    ]
