# Generated by Django 5.1.6 on 2025-03-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='destaque',
            new_name='servico',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='mais_vendido',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='premium',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='promo',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='tamanho',
        ),
        migrations.AddField(
            model_name='produto',
            name='litros',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(default='descreva o produto/serviço', max_length=255),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='chopps/'),
        ),
    ]
