# Generated by Django 5.1.6 on 2025-03-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_rename_destaque_produto_servico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('taxa', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
