# Generated by Django 5.1.6 on 2025-03-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_cidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='destaque',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produto',
            name='mais_vendido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produto',
            name='premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produto',
            name='promo',
            field=models.BooleanField(default=False),
        ),
    ]
