# Generated by Django 5.1.6 on 2025-03-08 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_produto_destaque_produto_mais_vendido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media/'),
        ),
    ]
