# Generated by Django 5.1.6 on 2025-02-18 03:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cep',
            field=models.CharField(default='00000000', max_length=8),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='data_cobrar',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 20, 3, 51, 12, 12453, tzinfo=datetime.timezone.utc)),
        ),
    ]
