# Generated by Django 5.1.6 on 2025-03-01 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_usuario_cep_alter_usuario_data_cobrar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='data_cobrar',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 31, 12, 27, 17, 669111, tzinfo=datetime.timezone.utc)),
        ),
    ]
