# Generated by Django 5.1.6 on 2025-03-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_usuario_data_cobrar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='data_cobrar',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='data_pagamento',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='status_pagamento',
        ),
        migrations.AddField(
            model_name='evento',
            name='cep',
            field=models.CharField(default=0, max_length=8),
        ),
    ]
