# Generated by Django 5.1.7 on 2025-03-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_usuario_cep_remove_usuario_data_cobrar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chopeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('bomba', 'Chopeira Bomba'), ('eletrica', 'Chopeira Elétrica')], max_length=10, unique=True)),
            ],
        ),
    ]
