# Generated by Django 5.1.7 on 2025-03-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_chopeira'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='chopeiras',
            field=models.ManyToManyField(to='authentication.chopeira'),
        ),
    ]
