# Generated by Django 5.1.7 on 2025-03-19 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_evento_chopeiras'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='hora_evento',
            field=models.TimeField(null=True),
        ),
    ]
