# Generated by Django 5.1.7 on 2025-03-19 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_evento_hora_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='bairro',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cep',
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rua',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
