# Generated by Django 5.1.7 on 2025-03-19 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_usuario_bairro_usuario_cep_usuario_rua'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cep',
        ),
    ]
