# Generated by Django 5.1.1 on 2025-02-08 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('cep', models.CharField(max_length=8)),
                ('cidade', models.CharField(max_length=100)),
                ('rua', models.CharField(max_length=130)),
                ('numero', models.CharField(max_length=5)),
            ],
        ),
    ]
