# Generated by Django 5.1.7 on 2025-03-20 18:30

import django.db.models.deletion
import parceiros.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('cep', models.CharField(max_length=8)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('rua', models.CharField(blank=True, max_length=130, null=True)),
                ('numero', models.CharField(max_length=5)),
                ('imagem', models.ImageField(blank=True, upload_to=parceiros.models.salvar_no_diretorio_do_user)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
