# Generated by Django 5.1.6 on 2025-03-04 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testemunho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_evento', models.CharField(max_length=50)),
                ('data_evento', models.DateField(auto_now_add=True)),
                ('feedback', models.TextField()),
            ],
        ),
    ]
